name: SpreadsheetImporter
version: 1.0
description: Imports spreadsheets
author: uziza

main: user.uziza.SheetImporter.SheetImporter

commands:
  import:
    usage: /import (FileName)
    description: import
  char:
    usage: /char (Character)
    description: load char
  desc:
     usage: /desc "Perk" type
     description: reads desc